server:
  port: 8080
  servlet:
    session:
      timeout: 30m
      cookie:
        name: QUIZ_SESSION
        http-only: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam_system?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 11111111

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.examsystem.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.examsystem: debug
